☁️ Automation

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -16,7 +16,9 @@ includes:
   ci:github: ./.config/taskfiles/ci/Taskfile-github.yml
   common: ./.config/taskfiles/common/Taskfile.yml
   common:code: ./.config/taskfiles/common/Taskfile-code.yml
+  common:start: ./.config/taskfiles/common/Taskfile-start.yml
   common:update: ./.config/taskfiles/common/Taskfile-update.yml
+  common:util: ./.config/taskfiles/common/Taskfile-util.yml
   docker: ./.config/taskfiles/docker/Taskfile.yml
   docker:build: ./.config/taskfiles/docker/Taskfile-build.yml
   docker:test: ./.config/taskfiles/docker/Taskfile-test.yml
@@ -25,6 +27,7 @@ includes:
   git: ./.config/taskfiles/git/Taskfile.yml
   git:github: ./.config/taskfiles/git/Taskfile-github.yml
   git:gitlab: ./.config/taskfiles/git/Taskfile-gitlab.yml
+  git:gitomatic: ./.config/taskfiles/git/Taskfile-gitomatic.yml
   git:hook: ./.config/taskfiles/git/Taskfile-hook.yml
   go: ./.config/taskfiles/go/Taskfile.yml
   go:goreleaser: ./.config/taskfiles/go/Taskfile-goreleaser.yml
@@ -33,9 +36,11 @@ includes:
   install: ./.config/taskfiles/install/Taskfile.yml
   install:ansible: ./.config/taskfiles/install/Taskfile-ansible.yml
   install:apt: ./.config/taskfiles/install/Taskfile-apt.yml
+  install:gh: ./.config/taskfiles/install/Taskfile-gh.yml
   install:github: ./.config/taskfiles/install/Taskfile-github.yml
   install:go: ./.config/taskfiles/install/Taskfile-go.yml
   install:npm: ./.config/taskfiles/install/Taskfile-npm.yml
+  install:pipx: ./.config/taskfiles/install/Taskfile-pipx.yml
   install:python: ./.config/taskfiles/install/Taskfile-python.yml
   install:rust: ./.config/taskfiles/install/Taskfile-rust.yml
   install:software: ./.config/taskfiles/install/Taskfile-software.yml
@@ -85,8 +90,20 @@ includes:
 output: interleaved
 
 vars:
-  DOCKERHUB_PROFILE: megabytelabs
-  DOCKERHUB_USER: professormanhattan
+  DOCKERHUB_PROFILE:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+        echo "$(jq -r '.profile.dockerhub' .config/variables.json)"
+      else
+        echo 'megabytelabs'
+      fi
+  DOCKERHUB_USER:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+        echo "$(jq -r '.profile.dockerHubUser' .config/variables.json)"
+      else
+        echo 'ProfessorManhattan'
+      fi
   ESLINT_FIX_RECURSIVE: 'true'
   ESLINT_FORMATTER: stylish
   ESLINT_FORMATTER_OPTIONS: git-log gitlab pretty summary
@@ -97,34 +114,60 @@ vars:
       if [ -f meta/main.yml ]; then
         grep namespace < meta/main.yml | sed 's/.*namespace: \\(.*\\)$/\\1/g'
       else
-        echo 'professormanhattan'
+        if [ -f .config/variables.json ] && type jq &> /dev/null; then
+          echo "$(jq -r '.profile.galaxy' .config/variables.json)"
+        else
+          echo 'ProfessorManhattan'
+        fi
       fi
   GALAXY_ROLE_NAME:
     sh: "if [ -f meta/main.yml ]; then grep role_name < meta/main.yml | sed 's/.*role_name: \\(.*\\)$/\\1/g'; fi"
-  GITHUB_ORG: ProfessorManhattan
-  GITHUB_USER: ProfessorManhattan
+  GITHUB_ORG:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+         echo "$(jq -r '.profile.github' .config/variables.json)"
+      else
+        echo 'megabytelabs'
+      fi
+  GITHUB_USER:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+         echo "$(jq -r '.profile.github' .config/variables.json)"
+      else
+        echo 'ProfessorManhattan'
+      fi
   GROUP_EXEC_ASYNC: 'false'
-  IGNORE_FOLDERS: -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*'
-    -o -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*'
-    -o -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*'
-    -o -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml
-    -o -name package-lock.json -o -name poetry.lock -o -name '.variables.json'
+  # yamllint disable rule:line-length
+  IGNORE_FOLDERS: >-
+    -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*' -o
+    -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*' -o
+    -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*' -o
+    -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml -o
+    -name package-lock.json -o -name poetry.lock -o -name '.variables.json'
   INIT_SCRIPT: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/scripts/update-init.sh
   LOG_FIX:
     sh: chmod +x .config/log
   MODEL_TASKFILE: https://gitlab.com/megabyte-labs/common/shared/-/raw/master/Taskfile.yml
-  NPM_KEEP_UPDATED: glob
+  NPM_KEEP_UPDATED: ''
   NPM_PROGRAM: npm
-  NPM_PROGRAM_LOCAL: pnpm
-  NPX_HANDLE: 'pnpx '
-  NPX_PACKAGE: pnpx
-  # yamllint disable rule:line-length
+  NPM_PROGRAM_LOCAL:
+    sh: |
+      if type pnpm &> /dev/null; then
+        echo 'pnpm'
+      elif type npm &> /dev/null; then
+        echo 'npm'
+      fi
+  NPX_HANDLE:
+    sh: |
+      if type pnpx &> /dev/null; then
+        echo 'pnpx '
+      elif type pnpm &> /dev/null; then
+        echo 'pnpm '
+      fi
   PROJECT_TYPE:
     sh: |
-      # yamllint disable-line rule:line-length
-      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="docker"; else TYPE="$VER"; fi; else TYPE="docker"; fi
-      # yamllint disable-line rule:line-length
-      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.subgroup' package.json)"; if [ "$VER" == 'null' ]; then SUBTYPE="codeclimate"; else SUBTYPE="$VER"; fi; else SUBTYPE="codeclimate"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="$GROUP_TYPE"; else TYPE="$VER"; fi; else TYPE="$GROUP_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.subgroup' package.json)"; if [ "$VER" == 'null' ]; then SUBTYPE="$REPOSITORY_TYPE"; else SUBTYPE="$VER"; fi; else SUBTYPE="$REPOSITORY_TYPE"; fi
       if [ "$TYPE" == 'common' ] && [ "$SUBTYPE" == 'shared' ]; then
         echo 'shared'
       elif [ "$TYPE" == 'common' ]; then
@@ -137,23 +180,39 @@ vars:
         echo 'project'
       fi
   # yamllint enable rule:line-length
-  PYTHON_HANDLE: 'poetry run '
+  PYTHON_HANDLE:
+    sh: |
+      if type poetry > /dev/null; then
+        echo 'poetry run '
+      else
+        echo ''
+      fi
   PYTHON_VIRTUALENV: true
   REPOSITORY_SUBTYPE:
     sh: |
+      if [ -n "$REPOSITORY_TYPE" ]; then REPO_SUBTYPE="$REPOSITORY_TYPE"; fi
       if type jq &> /dev/null && [ -f package.json ]; then
         VER="$(jq -r '.blueprint.subgroup' package.json)"
-        if [ "$VER" == 'null' ]; then echo "codeclimate"; else echo "$VER"; fi
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
       else
-        echo "codeclimate"
+        if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
       fi
   REPOSITORY_TYPE:
     sh: |
+      if [ -n "$GROUP_TYPE" ]; then REPO_TYPE="$GROUP_TYPE"; fi
       if type jq &> /dev/null && [ -f package.json ]; then
         VER="$(jq -r '.blueprint.group' package.json)"
-        if [ "$VER" == 'null' ]; then echo "docker"; else echo "$VER"; fi
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
       else
-        echo "docker"
+        if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
       fi
   SEMANTIC_CONFIG: semantic-release-config
   TIMEZONE: America/New_York
@@ -280,16 +339,22 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         HUSKY=0 git commit -m "{{.CLI_ARGS}}" --no-verify
         {{else}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         git commit
         {{end}}
 
   commit:quick:
+    deps:
+      - ci:commit:config
     cmds:
-      - git add --all
+      - |
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+        git add --all
       - HUSKY=0 git commit -m '🔧 chore(tweak): quick minor update' --no-verify
       - git push origin master
 
@@ -376,8 +441,7 @@ tasks:
     cmds:
       - git init
       - task: repair
-      - task: ci:commit
-      - task: ci:synchronize
+      - task: prepare
 
   lint:
     desc: Lints the project using all linters
@@ -594,10 +658,7 @@ tasks:
 
   repair:
     cmds:
-      - |
-        TMP="$(mktemp)" && curl -sSL {{.MODEL_TASKFILE}} > "$TMP"
-        .config/log info 'Ensuring new additions to the model `Taskfile.yml` are present in the project `Taskfile.yml`'
-        yq eval-all -i 'select(fileIndex == 0) * select(fileIndex == 1)' "$TMP" Taskfile.yml
+      - task: common:repair
       - |
         if [ -n "$UPDATE_INIT_SCRIPT" ]; then
           bash <(curl -sSL "$UPDATE_INIT_SCRIPT")
@@ -702,6 +763,30 @@ tasks:
       - task: common:shell
 
   start:
+    desc: Start the project by installing / updating dependencies, repairing issues, and opening a tutorial
+    summary: |
+      # Start the Project
+
+      This task does everything that running `bash start.sh` does plus a little bit more:
+
+      1. Installs Homebrew if it is not already installed
+      2. Ensures Bodega is installed and up-to-date
+      3. Ensures common system dependencies and runtimes
+      4. Installs commonly used CLI tools
+      5. Ensures local dependencies such as `node_modules` are installed
+      6. Attempts to repair the project if it detects any issues
+
+      It basically sets up all the tools you need, in advance so that problems can be detected as early
+      as possible. In some cases, this command will open documentation or a tutorial to read while dependencies are being
+      installed.
+    log:
+      error: Yikes! Error starting the project!
+      start: Starting the project..
+      success: Project started!
+    cmds:
+      - task: common:start
+
+  synchronize:
     desc: Set up the project and refresh it with the latest changes
     summary: |
       # Start the Project
@@ -721,6 +806,35 @@ tasks:
       success: Successfully synchronized the project with upstream file changes and also bootstrapped the project
     cmds:
       - task: upstream:{{.PROJECT_TYPE}}
+
+  tag:deps:
+    desc: Inject a new command in the `Taskfile.yml` that includes all tasks matching a given tag as deps
+    summary: |
+      # Create Task with Deps Based on Tag
+
+      Use this task to inject a new task in the `Taskfile.yml` that includes all the tasks
+      that are tagged with a certain tag as deps. The tag must be supplied as a CLI argument.
+
+      Say you have a task that looks like this:
+
+      ```
+      my-task:
+        tags:
+          - docker
+        cmds:
+          - docker volume ls
+      ```
+
+      Then, by running `task tag:deps -- docker`, you will get the following task injected into the
+      `Taskfile.yml` file:
+
+      ```
+      deps:docker:
+        deps:
+          - my-task
+      ```
+    cmds:
+      - task: common:util:task:tag:deps
 
   template:
     deps:
@@ -766,21 +880,29 @@ tasks:
         fi
 
   update:
-    desc: Update the repository
+    desc: Fully update the repository
+    summary: |
+      # Update the Repository / Project
+
+      This task will:
+
+      1. Ensure Homebrew is installed
+      2. Ensure runtimes like Node.js, Go, Python, and Poetry are installed
+      3. Ensure the `PATH` environment variable is properly configured
+      4. Configure the environment if it is in a `$CI` environment
+      5. Run a repair script that is used to ensure older repositories are compatible with the Taskfile scripts
+      6. Prepare the repository by automatically setting up certain parts of the project
+      7. Run a full update on the repository with `task start`
+      8. Automatically commit changes
+      9. Update GitLab/GitHub repository settings if the `GITHUB_TOKEN` / `GITLAB_TOKEN` variables are set
+
+      Along the way, if any dependencies are missing they will be installed as well just like with all of the
+      tasks included in these Taskfiles.
     log:
       error: Failed to update the repository
       start: Updating the repository..
       success: Finished updating the repository
     cmds:
-      - |
-        if ! type brew > /dev/null; then
-          task install:software:brew
-          . "$HOME/.profile"
-        fi
-        if ! type jq > /dev/null || ! type yq > /dev/null || ! type node > /dev/null || ! type go > /dev/null || ! type poetry > /dev/null; then
-          task update:prereqs
-          . "$HOME/.profile"
-        fi
-        task update:init
-        task prepare
-        task update:finish
+      - task: common:start
+        env:
+          UPDATE_PROJECT: 'true'
